# Generated by Django 2.2.2 on 2020-02-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='cover_image',
        ),
    ]
