# Generated by Django 2.2.2 on 2020-03-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200310_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_level',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
