# Generated by Django 2.2.2 on 2020-02-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_jobcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
